### ISSUE TITLE
Content-Type: application/x-gzip

### ISSUE THREAD

**Issue by mozai** [tricksterproxy/trickster#216]
Strange behaviour by Trickster, I can reproduce it where I am, and co-workers see it too, but not sure how to recreate it in a lab.

When using Trickster 1.0.4 as a data source with Grafana, Trickster is responding with strange http headers:  "Content-Encoding: gzip" and "Content-Type: application/x-gzip".  Shouldn't that be "Content-Type: application/json" ?

```
GET /api/v1/query_range?query=node_load5%7Brole%3D%22tls_alerts%22%2Cip%3D~%22.*%22%7D&start=1556133300&end=1556136960&step=60&timeout=1m HTTP/1.1
Host: gis-trickster-mog.[redacted]:9090
User-Agent: Grafana/5.4.3
Accept: application/json, text/plain, */*
Accept-Encoding: gzip, deflate, br
Accept-Language: en-CA,en-US;q=0.7,en;q=0.3
X-Forwarded-For: 10.137.16.75, 127.0.0.1, 127.0.0.1
X-Forwarded-Server: picasso.[redacted]
X-Grafana-Org-Id: 1

20:14:16.451737 IP gis-trickster-mog.[redacted].9090 > tls-oms-tsg.[redacted].33792: Flags [P.], seq 7261:8083, ack 4684, win 82, options [nop,nop,TS val 17771021 ecr 3234733124], length 822
E..j..@.@...
l..
k.'#.......2.0....R w.....
..*....DHTTP/1.1 200 OK
Access-Control-Allow-Origin: *
Content-Encoding: gzip
Vary: Accept-Encoding
X-Accelerator: trickster 1.0.4
Date: Wed, 24 Apr 2019 20:14:16 GMT
Content-Length: 600
Content-Type: application/x-gzip
```

Bizarrely, I'm unable to reproduce it using curl and "-H" parameters to duplicate the HTTP request sent by Grafana, I even get extra headers in the response. When I use curl I get "Content-Type: application/json" but when I tcpdump the request from Grafana I see "Content-Type: application/x-gzip".  The latter should only happen if it was a gzipped file on-disk that was compressed a second time (encoded) by gzip again.

```
GET /api/v1/query_range?query=node_load5%7Brole%3D%22tls_alerts%22%2Cip%3D~%22.*%22%7D&start=1556133300&end=1556136960&step=60&timeout=1m HTTP/1.1
Host: gis-trickster-mog.[redacted]:9090
User-Agent: Grafana/5.4.3
Accept: application/json, text/plain, */*
Accept-Encoding: gzip, deflate, br
Accept-Language: en-CA,en-US;q=0.7,en;q=0.3
X-Forwarded-For: 10.137.16.75, 127.0.0.1, 127.0.0.1
X-Forwarded-Server: picasso.[redacted]
X-Grafana-Org-Id: 1


20:25:56.315641 IP gis-trickster-mog.[redacted].9090 > tls-ops-tsg.[redacted].54730: Flags [.], ack 472, win 59, options [nop,nop,TS val 17945987 ecr 1813927573], length 0
E..4.%@.@...
l..
k.
#.......a......;.$.....
....l.V.
20:25:56.326700 IP gis-trickster-mog.[redacted].9090 > tls-ops-tsg.[redacted].54730: Flags [P.], seq 1:962, ack 472, win 59, options [nop,nop,TS val 17945990 ecr 1813927573], length 961
E....&@.@...
l..
k.
#.......a......; ......
....l.V.HTTP/1.1 200 OK
Access-Control-Allow-Headers: Accept, Accept-Encoding, Authorization, Content-Type, Origin
Access-Control-Allow-Methods: GET, OPTIONS
Access-Control-Allow-Origin: *
Access-Control-Expose-Headers: Date
Content-Encoding: gzip
Content-Type: application/json
Date: Wed, 24 Apr 2019 20:25:56 GMT
Vary: Accept-Encoding
X-Accelerator: trickster 1.0.4
Content-Length: 568
```

The obvious answer is "well stop using Grafana, then."  But I feel the anomalous "Content-Type: application/x-gzip" from Trickster is worth checking.

**Comment by jranson** [comment]
Thanks for the report, I will definitely check this out!

**Comment by hatemosphere** [comment]
We're actually having the same behavior - sometimes getting random "Content-Encoding: x-gzip" headers (at lest in latest Firefox stable  build) and it breaks Grafana.

**Comment by jranson** [comment]
I believe we have root-caused this issue and will be working the fix today.

The issue has roots in an improvement was introduced in the first cut of Trickster 1.0 to support requesting and accepting gzipped responses from the upstream origin, in order to reduce bandwidth between Trickster and the upstream origin (obviously a good thing!)

In the situation of a full cache miss of a given query, we both cache the object returned from the upstream (inflated and then compressed with snappy) and concurrently serve it back down to the user (untransformed with the original gzip compression). What we have found, however, is that the Gorilla Compression Handler (implemented as middleware for every request Trickster serves since 0.0.x) blindly compresses the response without checking to see if the content encoding is _already_ gzip. So these passthroughs on cache miss are being double-gzipped, once by the upstream, and once for downstream by Gorilla. This is not an issue for cache hits or partial cache hits, as they are un-snappy'd from cache and Gorilla properly gzips those when responding to the client. Thus it only affects full cache misses. This is not an issue in 0.1.x because, since we do not support upstream compressed responses in 0.1.x, proxied content is always safe for Gorilla. 

I would prefer that we _don't_ uncompress these cache miss objects within Trickster, simply for Gorilla to recompress them immediately, as that would be a lot of unnecessary compute.  Instead, I would prefer to find a way to selectively skip over the Gorilla Compress Handler when the response is already known to be gzipped, by examining the existing Content-Encoding headers. The way we will likely go about this is to write a very small custom middleware around the Gorilla Compress Handler to do these checks and bypass or hand off to Gorilla as needed.

**Comment by jranson** [comment]
(Deleted previous comment as it was completely wrong).

All, PR #222 should fix this and we'll try to get a release cut later today. Thank you for the report!

**Comment by jranson** [comment]
The main root cause was that the upstream response headers (incl Content-Type) were not being passed down on a Cache Miss, and it looks like firefox is much stricter about these things than Chrome. I have fixed that up and also corrected an issue where certain cache misses were being marked as range misses by mistake.

**Comment by ti-mo** [comment]
Hi @jranson, sorry to revive this; is it possible that this patch didn't make it into 0.1.10? I'm still seeing this error. Running the following build:
```
    image: tricksterio/trickster:0.1.10
    imageID: docker-pullable://tricksterio/trickster@sha256:17ca55b10137c7c2ca3a83f180612adc59861a8c2c066658e96a41bfabf6b459
```

**Comment by jranson** [comment]
@ti-mo it should have made it in but I will crawl through the code and see what might have happened. If you are able to capture this, would you mind dropping a full snippet of response headers on here (and in particular, the `X-Trickster-Result` header. Thanks!

**Comment by ti-mo** [comment]
Hi @jranson

We're hitting Trickster through an `ingress-nginx` ingress controller, so client -> ingress is h/2. Shouldn't make a difference in terms of response headers, though. These are the response headers as seen on the browser:

```
HTTP/2.0 200 OK
server: nginx/1.13.12
date: Sat, 21 Sep 2019 17:19:23 GMT
content-type: application/x-gzip
content-length: 613
access-control-allow-origin: *
content-encoding: gzip
strict-transport-security: max-age=15724800; includeSubDomains
vary: Accept-Encoding
x-frame-options: deny
X-Firefox-Spdy: h2
```

`X-Trickster-Result` is not present in the response, as it was introduced in `1.0.6-beta6` according to the changelog.

**Comment by jranson** [comment]
@ti-mo wanted to check in on this issue and see if 1) are you still having issues upgrading to a more recent beta, and 2) if so, are you still experiencing this issue? Thanks for letting us know. We will close the issue next week if there is no additional activity.

**Comment by jranson** [comment]
closing due to in activity
